### ISSUE TITLE
Where does 3DMM storage movie music (NOT "BUILDING" MUSIC)

### ISSUE THREAD

**Issue by Marksonthehost** [foone/3DMMForever#44]
I found for them everywhere, but I only found building musics in the BULIDING folder

**Comment by MishaTy** [comment]
I think they are stored in the 3TH files, which the source code is missing.

**Comment by frank-weindel** [comment]
They are located in content-files/snds.3cn. Each one is a MIDS chunk. You can extract them with 3DMM Pencil but they aren't raw .midi files that will play in a standard MIDI player. There's some conversion that needs to be done to them that I don't recall right now.

**Comment by frank-weindel** [comment]
@foone Do you recall?

**Comment by MishaTy** [comment]
![image](https://user-images.githubusercontent.com/46088515/230230880-49d8e4a6-e07a-4d8a-9501-2551479f42be.png)

**Comment by MishaTy** [comment]
Also found these zip archives with all of the music:
https://3dmmfiles.com/uploads/jayrod/misc/doraemon-midi.zip
https://3dmmfiles.com/uploads/philwilliamson/3dmm_mids.zip

**Comment by foone** [comment]
Assuming Jayrod is right about this (which I have no reason to doubt), maybe we should mass-convert the MIDS chunks back to standard MID files, then add a build step to de-header them? 
Super low priority, of course, but it'd make it easy to pull the MIDI out of the source or swap in new MIDI (though I'm not sure why you'd want to do that)

**Comment by mdtauk** [comment]
Ideally every piece of content should be decompiled to editable or adaptable formats, which are compiled to byte accurate CHUNK files.

In time when the  enhanced version comes out, mods and add on content can be created.

Not a priority compared to modernising the code base itself, but at some stage the studios and companies that created the content used in 3DMM would have provided source files which were compiled and included - so it is in scope for the source repo IMO

**Comment by Marksonthehost** [comment]
I see, those SFX and MIDI files are storaged in SNDS.3CN, use a tool called Chunk Explorer to extract them:
http://3dmmfiles.com/uploads/philwilliamson/ChunkExplorer-v2.0.0.1.zip
Anyway, thank you for your guys helping
